### ISSUE TITLE
Bug: Layers with alpha translucency darker when flattened

### ISSUE THREAD

**Issue by hemebond** [FHPythonUtils/GimpFormats#12]
### Describe the bug

Using the head of the master branch, if layers have alpha channels, any alpha value less than 1 will end up darker than it should (based on the export from Gimp)

[variable-alpha.zip](https://github.com/FHPythonUtils/GimpFormats/files/7698163/variable-alpha.zip)

### Expected outcome

![expected](https://user-images.githubusercontent.com/424218/145701802-cfa0e7ac-b158-46e0-bb92-886a874270ab.png)

### Actual outcome
![actual](https://user-images.githubusercontent.com/424218/145701801-8cf7befe-5875-43ff-bf01-fb8cbe513820.png)

**Comment by hemebond** [comment]
Testing with PIL directly the issue seems to be there so I am currently testing different methods of combining the layers. Does not appear to be an issue in GimpFormats, but instead in PIL.

**Comment by hemebond** [comment]
Closing this out because it's not a bug in GimpFormats and might not even be a bug. I'm getting inconsistent results in my tests.

**Comment by ali1234** [comment]
This does seem to be gimp being weird. 50% white over 100% black = 73% grey, not 50% as you would expect. I am still trying to figure out why it does this, and precisely what calculation it is doing.

**Comment by ali1234** [comment]
You can also keep on using Default layers and change the composite space to perceptual (right click the layer).
