### ISSUE TITLE
I made a compatibility test suite

### ISSUE THREAD

**Issue by ali1234** [FHPythonUtils/GimpFormats#13]
See https://xcf.zerostem.io/

This tool uses gimp scripting to generate xcf files with various combinations of layer blending. It exports each one as a png with gimp, gimpformats, layeredimage, and xcftools and compares the results. In gimpformats the conversion is done like this:

    img = GimpDocument(...)
    img.image.save(...)

Then it compares the png files. If any channel value differs by more than 8 then the test fails.

Of 648 tests, 550 failed.

**Comment by FredHappyface** [comment]
Cheers for the issue. Unfortunately I do not have the bandwidth to address the test failures per https://github.com/FHPythonUtils/GimpFormats/issues/1. 

Affected users can do one of the following:
- Work around these by using simple layers etc 
- Consider contributing to the project to improve the correctness of the compositor 
- Consider using alternative software that meets their needs 
- Consider saving in ORA or some more supported format
