### ISSUE TITLE
Crash when merging XCF containing layer groups

### ISSUE THREAD

**Issue by ali1234** [FHPythonUtils/GimpFormats#4]
To reproduce:

1. Open GIMP, make a new image, add a layer group, drag the background layer into it, and save as `test.xcf`.
2. Code:

```python3
from gimpformats.gimpXcfDocument import GimpDocument

img = GimpDocument('test.xcf')
img.image.show()
```

Result:
```
Traceback (most recent call last):
  File "tst.py", line 4, in <module>
    img.image.show()
  File "venv/lib/python3.8/site-packages/gimpformats/gimpXcfDocument.py", line 335, in image
    while layers[index].itemPath is not None:
IndexError: list index out of range

```

Expected result: The merged image is displayed.

File which causes the error: [test.xcf.gz](https://github.com/FHPythonUtils/GimpFormats/files/6605217/test.xcf.gz)

**Comment by ali1234** [comment]
PS Reason why I need this:

I value non-destructive editing and to that end, all the sprites for my game extensively use layer groups which are used to generate the final game assets - alpha mask, blending, actual colours etc. So I need to be able to load an XCF, set some subset of layers and layer groups visible or invisible, and then render to a PIL image for further processing. Currently I do this using GIMP's built-in Python scripting engine, but this is not very CI-friendly as it requires a full GIMP install.

**Comment by FredHappyface** [comment]
Thanks for raising this! It's a bug in the test program and is a general issue with how gimpformats represents an xcf. I'd highly recommend using layeredimage as I've worked around many of these painful issues 

The reader you will want is at https://github.com/FHPythonUtils/LayeredImage/blob/master/layeredimage/io/xcf.py but I'll also add this in the next push. Hope this helps somewhat

**Comment by ali1234** [comment]
Thanks. I tried layeredimage and I was able to get it to generate an image after some hacking, but it doesn't look right. I just get a white square instead of my sprites. Seems like something to do with how the layers are blended. I am investigating.
