### ISSUE TITLE
Feature: Support group and layer masks when flattening

### ISSUE THREAD

**Issue by hemebond** [FHPythonUtils/GimpFormats#6]
## Feature
When flattening an XcfDocument with `flattenAll` it does not look the way it does when exported from GIMP. Masks seem to be ignored whether on a layer or on a group.

### Describe the solution you'd like
`flattenAll` should result in the same image one would get if viewed in, or exported from, GIMP.

Group masks should be applied to all layers inside the group. A layer mask should be applied to its layer.

**Comment by FredHappyface** [comment]
Can you provide an example xcf please and I'll take a look

**Comment by hemebond** [comment]
This is the XCF I'm currently using to test various workarounds.

[xcf_mask_test.zip](https://github.com/FHPythonUtils/GimpFormats/files/6937133/xcf_mask_test.zip)

**Comment by hemebond** [comment]
Just FYI, I've managed to work around it by applying layer and parent layer group masks to each layer, setting visible=False on all layer groups, and then calling flattenAll.

**Comment by FredHappyface** [comment]
Hmm yeah that definitely sounds like a bug. I'll take a look over the next week 🙂

**Comment by FredHappyface** [comment]
Done in version 2021.1 :)
